<div bind:this={mapContainer} class="map"></div>

<script>
    import { onMount } from "svelte";
    import mapboxgl from "mapbox-gl";
    import "mapbox-gl/dist/mapbox-gl.css";
    import * as turf from "@turf/turf";

    let {
        onBenchSelect,
        backrest = "any",
        material = "any",
        nearWater = false,
        nearGreen = false,
        searchText = "",
        clearSelectedBenchSignal = 0
    } = $props();

    /** @type {HTMLDivElement | null} */
    let mapContainer;
    /** @type {mapboxgl.Map | null} */
    let map;

    /** @type {Set<string>} */
    let nearWaterIds = new Set();

    /** @type {Set<string>} */
    let nearGreenIds = new Set();

    let spatialDataReady = $state(false);

    let benchesLayerReady = $state(false);

    async function loadSpatialFilters() {
        const benchesResponse = await fetch("/data/bamberg_benches.geojson");
        const waterResponse = await fetch("/data/bamberg_water.geojson");
        const greenResponse = await fetch("/data/bamberg_green.geojson");

        const benches = await benchesResponse.json();
        const water = await waterResponse.json();
        const green = await greenResponse.json();

        nearWaterIds = getNearbyBenchIds(benches, water, 15); 
        nearGreenIds = getNearbyBenchIds(benches, green, 10); 

        spatialDataReady = true;
    }


/*The console kept reporting problems - "parameter '...' has an 'any' type". The type definitions and parameters are debugged und generated by Chatgpt. */
    /**
     * @typedef {import("geojson").FeatureCollection} FeatureCollection
     * @typedef {import("geojson").Feature} Feature
     */
    /**
     * @param {FeatureCollection} benches
     * @param {FeatureCollection} targetGeoJson
     * @param {number} distanceMeters
     * @returns {Set<string>}
     */
    /*Get Ids of the benches that fall into the buffer 'near water' or 'near green'.*/
    function getNearbyBenchIds(benches, targetGeoJson, distanceMeters) {
        const ids = new Set();

        const bufferedFeatures = targetGeoJson.features
            .filter((feature) => feature.geometry)
            .map((feature) =>
                turf.buffer(feature, distanceMeters, { units: "meters" })
            )
            .filter(Boolean);

        for (const bench of benches.features) {
            if (!bench.geometry || bench.geometry.type !== "Point") continue;

            const benchId =
                bench.properties?.["@id"] ||
                bench.properties?.id;

            if (!benchId) continue;

            const benchPoint = turf.point(bench.geometry.coordinates);

            const isNearby = bufferedFeatures.some((bufferedFeature) =>
                turf.booleanPointInPolygon(
                    benchPoint,
                    /** @type {any} */ (bufferedFeature)
                )
            );

            if (isNearby) {
                ids.add(benchId);
            }
        }

        return ids;
    }

    mapboxgl.accessToken = import.meta.env.VITE_MAPBOX_TOKEN;
       
    onMount(() => {
        if (!mapContainer) return;

        map = new mapboxgl.Map({

            container: mapContainer,

            style: "mapbox://styles/mapbox/standard",

            center: [10.8976, 49.8874],

            zoom: 12

        });

        map.on('load', () => {
            if (!map) return;

            map.loadImage('/icons/bench.png', (err, image) =>{
                if (err || !image || !map) throw err;

                if (!map.hasImage('bench')){
                    map.addImage('bench', image);
                }
            })

            map.loadImage('/icons/bench-backrest.png', (err, image) =>{
                if (err || !image || !map) throw err;

                if (!map.hasImage('bench-backrest')){
                    map.addImage('bench-backrest', image);
                }
            })

            map.addSource('bamberg', {
                type: 'geojson',
                data: '/data/bamberg_boundaries.geojson'
            });

            map.addSource('benches', {
                type: 'geojson',
                data: '/data/bamberg_benches.geojson'
            })

            map.addLayer({
                id: 'bamberg-fill',
                type: 'fill',
                source: 'bamberg',
                paint: {
                'fill-color': '#4CAF50',
                'fill-opacity': 0.1
                }
            });

            map.addLayer({
                id: 'bamberg-outline',
                type: 'line',
                source: 'bamberg',
                paint: {
                'line-width': 4,
                'line-color': 'orange',
                'line-dasharray': [3,1],
                }
            });

            map.addLayer({
                id: 'benches',
                type:'symbol',
                source: 'benches',

                minzoom: 13,

                layout: {
                    'icon-image': [
                        'case',

                        ['==',['get', 'backrest'], 'yes'],
                        'bench-backrest',

                        'bench'
                    ],

                    'icon-size': 0.5,

                    'icon-allow-overlap': true
                }
            })

            map.addSource("selected-bench", {
                type: "geojson",
                data: {
                    type: "FeatureCollection",
                    features: []
                }
            });

            map.addLayer({
                id: "selected-bench-halo",
                type: "circle",
                source: "selected-bench",
                paint: {
                    "circle-radius": 12,
                    "circle-color": "#ff9f1c",
                    "circle-opacity": 0.35,
                    "circle-stroke-color": "#ff9f1c",
                    "circle-stroke-width": 2
                }
            });

            map.addLayer({
                id: "selected-bench",
                type: "symbol",
                source: "selected-bench",
                layout: {
                    "icon-image": [
                        "case",
                        ["==", ["get", "backrest"], "yes"],
                        "bench-backrest",
                        "bench"
                    ],
                    "icon-size": 0.8,
                    "icon-allow-overlap": true,
                    "icon-ignore-placement": true
                }
            });

            benchesLayerReady = true;
            loadSpatialFilters();

            map.on("click", "benches", (e) => {
                if (!e.features?.length) return;

                const clickedFeature = /** @type {any} */ (e.features[0]);
                const rawProps = clickedFeature.properties || {};

                const benchId =
                    rawProps["@id"] ||
                    rawProps.id ||
                    rawProps["@id".replace("@", "")];

                const selectedSource = map.getSource("selected-bench");

                if (selectedSource) {
                    selectedSource.setData({
                        type: "FeatureCollection",
                        features: [clickedFeature]
                    });
                }
                onBenchSelect({
                    ...rawProps,
                    id: rawProps["@id"]
                });
            });
        
        });
    });

    $effect(() => {
        if (!map || !benchesLayerReady) return;

        const text = searchText.trim().toLowerCase();

        /** @type {any[]} */
        let filter = ["all"];

        if (backrest !== "any") {
            filter.push(["==", ["get", "backrest"], backrest]);
        }

        if (material !== "any") {
            filter.push([
            "in",
            material,
            ["downcase", ["coalesce", ["get", "material"], ""]]
            ]);
        }

        if (text) {
            filter.push([
            "any",
            ["in", text, ["downcase", ["coalesce", ["get", "inscription"], ""]]],
            ["in", text, ["downcase", ["coalesce", ["get", "material"], ""]]]
            ]);
        }

        if (nearWater && spatialDataReady) {
            filter.push([
                "in",
                ["coalesce", ["get", "@id"], ["get", "id"]],
                ["literal", Array.from(nearWaterIds)]
            ]);
        }

        if (nearGreen && spatialDataReady) {
            filter.push([
                "in",
                ["coalesce", ["get", "@id"], ["get", "id"]],
                ["literal", Array.from(nearGreenIds)]
            ]);
        }

        map.setFilter("benches", filter.length > 1 ? filter : null);
    });

    $effect(() => {
        clearSelectedBenchSignal;

        if (!map || !map.getSource("selected-bench")) return;

        const selectedSource = /** @type {mapboxgl.GeoJSONSource} */ (
            map.getSource("selected-bench")
        );

        selectedSource.setData({
            type: "FeatureCollection",
            features: []
        });
    });
</script>

<style>
.map{
    width:100%;
    height:100%;
}
</style>